# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RequestListaUsuarios(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, peticion: str=None):  # noqa: E501
        """RequestListaUsuarios - a model defined in Swagger

        :param peticion: The peticion of this RequestListaUsuarios.  # noqa: E501
        :type peticion: str
        """
        self.swagger_types = {
            'peticion': str
        }

        self.attribute_map = {
            'peticion': 'peticion'
        }
        self._peticion = peticion

    @classmethod
    def from_dict(cls, dikt) -> 'RequestListaUsuarios':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Request_ListaUsuarios of this RequestListaUsuarios.  # noqa: E501
        :rtype: RequestListaUsuarios
        """
        return util.deserialize_model(dikt, cls)

    @property
    def peticion(self) -> str:
        """Gets the peticion of this RequestListaUsuarios.


        :return: The peticion of this RequestListaUsuarios.
        :rtype: str
        """
        return self._peticion

    @peticion.setter
    def peticion(self, peticion: str):
        """Sets the peticion of this RequestListaUsuarios.


        :param peticion: The peticion of this RequestListaUsuarios.
        :type peticion: str
        """
        if peticion is None:
            raise ValueError("Invalid value for `peticion`, must not be `None`")  # noqa: E501

        self._peticion = peticion
