# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RequestRecuperarClave(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, correo: str=None):  # noqa: E501
        """RequestRecuperarClave - a model defined in Swagger

        :param correo: The correo of this RequestRecuperarClave.  # noqa: E501
        :type correo: str
        """
        self.swagger_types = {
            'correo': str
        }

        self.attribute_map = {
            'correo': 'correo'
        }
        self._correo = correo

    @classmethod
    def from_dict(cls, dikt) -> 'RequestRecuperarClave':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Request_RecuperarClave of this RequestRecuperarClave.  # noqa: E501
        :rtype: RequestRecuperarClave
        """
        return util.deserialize_model(dikt, cls)

    @property
    def correo(self) -> str:
        """Gets the correo of this RequestRecuperarClave.


        :return: The correo of this RequestRecuperarClave.
        :rtype: str
        """
        return self._correo

    @correo.setter
    def correo(self, correo: str):
        """Sets the correo of this RequestRecuperarClave.


        :param correo: The correo of this RequestRecuperarClave.
        :type correo: str
        """
        if correo is None:
            raise ValueError("Invalid value for `correo`, must not be `None`")  # noqa: E501

        self._correo = correo
